### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by mshoaibdev** [torralbodavid/simple-recaptcha-v3#13]
Greate package, Can you please update it to Laravel 9. So I could use it in my project.

Big Thanks.

**Comment by torralbodavid** [comment]
Sure!

Feel free to use the new version 1.5.0 where Laravel 9 support has been added.

[v1.5.0](https://github.com/torralbodavid/simple-recaptcha-v3/releases/tag/v1.5.0)
