### ISSUE TITLE
Intermittent null recaptcha_response

### ISSUE THREAD

**Issue by HowardF** [torralbodavid/simple-recaptcha-v3#7]
Every now and again, I get error response as follows:

_ErrorException
Trying to access array offset on value of type null_

Points here:
_vendor/torralbodavid/simple-recaptcha-v3/src/Rules/Captcha.php:50_

Testing with standard auth login page running locally with valet.
Laravel 7
Php 7.4

Any idea what I might be doing wrong?

H

**Comment by torralbodavid** [comment]
Please update the package to the v1.2.1 version in order to fix ErrorException issue.

Then, check if you created reCaptcha v3 keys correctly and if there is not any javascript issues in your application.

**Comment by HowardF** [comment]
Thanks for looking into this.

Now I am getting javascript error: Uncaught ReferenceError: grecaptcha is not defined

**Comment by torralbodavid** [comment]
> Thanks for looking into this.
> 
> Now I am getting javascript error: Uncaught ReferenceError: grecaptcha is not defined

Be sure you have included at the very bottom of your head tag from the pages you want to protect with reCaptcha, the `@captcha_init` blade directive. This will start loading Google reCaptcha API.

Then, add inside your form, the `@captcha('action')` directive.

**Comment by HowardF** [comment]
Think we are good. Different error readings depending on browser. But directives are in place.
